---
- name: Application Services (AS3) playbook
  hosts: bigip
  connection: local

  tasks:
    - name: AS3 Push
      uri:
        url: https://bigip15.local/mgmt/shared/appsvcs/declare
        body_format: json
        status_code: [200, 202, 207]
        return_content: true
        headers:
          Content-Type: application/json
        body:
          {
            "class": "AS3",
            "action": "deploy",
            "declaration": {
              "class": "ADC",
              "schemaVersion": "3.26.0",
              "remark": "Creating external data group",
              "Common": {
    	          "Shared": {
                  "class": "Application",
                  "template": "shared",
			            "mydatagroup": {
                    "class": "Data_Group",
                    "label": "Tag values mapping",
                    "storageType": "external",
                    "keyDataType": "string",
                    "externalFilePath": "https://raw.githubusercontent.com/shaath1/externaldatagroup/main/data_group_sample.txt",
                    "separator": ":="
    		          }
    	          }
              }
            }
          }
        method: POST
        force_basic_auth: yes
        user: "admin"
        password: "admin"
        validate_certs: no
