- name: POST AT Declaration
  hosts: bigip
  connection: local

  tasks:

    - name: ATC POST
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration: "{{ lookup('template', 'j2as3.json.j2') }}"
        atc_declaration_file: "j2as3.json.j2"
        atc_delay: 10
        atc_retries: 5
        provider:
          server: bigip15.local
          server_port: "443"
          user: admin
          password: admin
          validate_certs: "false"

    # atc_AS3_status, atc_DO_status , atc_TS_status
    - debug: var=atc_AS3_status