---
- name: Application Services (AS3) playbook
  hosts: bigip
  connection: local
  vars_files: setup.yml 

  tasks:
    - name: AS3 Push
      uri:
        url: https://{{ bigip.address }}/mgmt/shared/appsvcs/declare
        body_format: json
        status_code: [200, 202, 207]
        return_content: true
        headers:
          Content-Type: application/json
        body: "{{ lookup('file','j2as3.json.j2') }}"
        body_format: json
        method: POST
        force_basic_auth: yes
        user: "{{ bigip.admin_user }}"
        password: "{{ bigip.admin_password }}"
        validate_certs: no
